# Generated by Django 3.2.7 on 2021-09-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Open"),
                            (1, "In Progress"),
                            (2, "Wont Fix"),
                            (3, "Resolved"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
    ]
